---
services:
  db:
    image: docker.io/postgres:15
    environment:
      POSTGRES_USER: python_starter_project
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  pgadmin:
    image: docker.io/dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: a@b.c
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8888:80"
