"""Add birth date to user

Revision ID: 249bdcf23bbc
Revises: ba721264aad6
Create Date: 2025-09-07 10:56:51.787628

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "249bdcf23bbc"
down_revision = "ba721264aad6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("date_of_birth", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "date_of_birth")
    # ### end Alembic commands ###
