"""Create users table

Revision ID: bda8a9a88fdb
Revises: 
Create Date: 2023-07-01 14:58:03.351986

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bda8a9a88fdb"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("surname", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
